name: Push

on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

jobs:
  push_docker:
    name: PUSH Docker Image
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
        - name: Check out the repo
          uses: actions/checkout@v2
          with:
            fetch-depth: 0
        - name: Log in to Docker Hub
          uses: docker/login-action@v1
          with:
              username: ${{ secrets.DOCKER_USER }}
              password: ${{ secrets.DOCKER_PASSWORD }}
        - name: Push to Docker Hub
          uses: docker/build-push-action@v2
          with:
              push: true
              tags: zapay/mongo-express:latest
              context: .
